image: "ruby:2.5"

before_script:
    - apt-get update -qq && apt-get install -y -qq sqlite3 libsqlite3-dev nodejs
    - ruby -v
    - which ruby
    - gem install bundler --no-document
    - bundle install --jobs $(nproc)  "${FLAGS[@]}"

rspec:
    script:
        - bundle exec rspec
    rubocop:
        script:
            - bundle exec rubocop



stages:
    - build
    - test
    - deploy

job 1:
    before_script:
        - docker info

    stage: build
    script:
        - docker build -t my-docker-image .

job 2:
    stage: pull
    script:
        - docker pull ubuntu:16.04


job 2:
    stage: test
    script: 
        - docker run my-docker-image
        - docker run -it --rm  ubuntu:16.04  echo "Hello from Ubuntu:6.04"


